### ISSUE TITLE
✨ Implement `get_slot()` and `get_epoch()`

### ISSUE THREAD

**Issue by jamesondh** [sedaprotocol/seda-chain-contracts#11]
## ✨ Feature

We need query functions to determine the current slot and epoch based on block height of the Cosmos chain. In the future we will use these functions for posting batches.

## Motivation

Slots are time windows in which batches (of data requests) can be posted (i.e. 1 batch per slot). After x slots, a new epoch occurs and a new committee of data request resolvers is selected.

## Implementation

Create new constants:
- `COSMOS_BLOCKS_PER_SEDA_SLOT`
- `SLOTS_PER_EPOCH`

Create new pure functions:
- `get_slot(block_height: u64)`
- `get_epoch(block_height: u64)`

Create new non-pure functions that use the [BlockInfo](https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.BlockInfo.html) to get the current block height:
- `get_current_slot()`
- `get_current_epoch()`

**Comment by Thomasvdam** [comment]
No longer relevant.
