### ISSUE TITLE
✨ Create `merklize()` function

### ISSUE THREAD

**Issue by jamesondh** [sedaprotocol/seda-chain-contracts#12]
## ✨ Feature

Create a `merklize()` function.

REQUIRES DISCUSSION: what kind of serialization? borsh?

## Motivation

For batch processing, we need to be able to merklize data requests from the pool to verify against the aggregated signature.

## Implementation

Create a `merklize()` function. Most of the code can be re-used from [seda-rust](https://github.com/sedaprotocol/seda-rust/blob/main/contracts/src/merkle.rs). Create a test with some strings.

**Comment by Thomasvdam** [comment]
No longer relevant as the chain takes care of batches.
