### ISSUE TITLE
🔧 Allowlist for multiple relayers

### ISSUE THREAD

**Issue by FranklinWaller** [sedaprotocol/seda-chain-contracts#140]
## 🔧 Chore

Put `post_data_request` behind an allow list. 

## Motivation

Right now we don't have incentives in place to support permission-less relayers. To mitigate attacks we temporarily enable an allow list on the creation of data requests. This allow list is goverend by the DAO/Gov module

**Comment by gluax** [comment]
Relayer has been removed, and solvers now exist. No longer needed.
