### ISSUE TITLE
✨ Standardise event attributes

### ISSUE THREAD

**Issue by Thomasvdam** [sedaprotocol/seda-chain-contracts#28]
## ✨ Feature

Make it easier to index SEDA events and extract all the desired information.

## Motivation

The data we get back when retrieving Tx logs is pretty unstructured which makes it pretty difficult to figure out where it actually originated and how it should be indexed. We’ve looked at a bunch of different CosmWasm chains (Tgrade, Osmosis, Secret, Mars) but as far as we can see they don’t do any special indexing and basically do what ping/mintscan/etc do and just echo mostly raw data back to the user.

This standardisation should help to implement: https://github.com/sedaprotocol/seda-explorer-be/issues/67 for the explorer. Bluntly put the aim is for the contracts/modules to have more control over what gets indexed in terms of SEDA entities (DRs, commits, reveals, binaries, etc).

## Implementation

While doing some reading I learned that it's possible to emit custom events from a CosmWasm contract, see https://github.com/CosmWasm/wasmd/blob/main/EVENTS.md. This would make indexing a lot easier and prevent a lot of additional key prefixes.

To decouple the release cycle of the network components and indexer we need to make a tighter coupling on the implementation level. In practice this means the following:

- All attribute information that needs to be indexed should be emitted in a custom event that uses the `seda-` prefix. On the Cosmos level a DR event will then look like `wasm-seda-data-request` where the `wasm-` prefix is injected by the `x/wasm` module. (exact name subject to change).
- Every action should result in a state change for a particular entity, (DR, commit, reveal, executor, etc). This entity should be part of the custom event name, with the value being a string matching the changed entity. Some suggestions: `"data_request"`, `"dr_commit"`, `"dr_reveal"`, `"dr_result"`/`"dr_tally"`, `"executor_stake"`, `"dr_wasm_binary"`, etc.
- In case there are multiple actions possible for an entity (create/delete) we add that to the event type. 
- It makes sense to version these as well in case we want to add/remove attributes later; a `version` attribute that has a SemVer value `"x.y.z"`.
- Ideally the emitted event contains all the required information to construct the latest state of the affected entity in the indexer.
  - However, there are many instances where we are interested in the delta as well. To support this we can store it in a new entity and store that separately. For example, DR executors can be rewarded/slashed and we'll want to show all these events. In that case we'll create an entity such as `"dr_executor_result"` (bad name, but bear with me) which contains the address, type (reward/slash), and amount.
  - If the contract/module does not have access to the full new state of an entity the indexer is responsible for making it right. Don't add a lot of additional complexity/computation just to get some extra data to the explorer.

## Input Mapping

While technically it’s possible to extract things like the input from the message this is a real pain in the backside, so ideally the contract/module just echoes it in the attributes. If it turns out that putting things in attributes has a (large) impact on gas consumption it's too bad and the explorer will have to suck it up.

A (perhaps too) simple way to test gas consumption for attributes is to input some ridiculously long string as a value in create_data_request and see what the average gas cost is, and then do it again while also echoing this input in the attributes and compare the average gas cost of this to the original.

**Comment by hacheigriega** [comment]
I confirmed that printing message inputs as attributes does not impact gas usage. But if we print things like Wasm byte code, transaction query results will be mostly taken up by super long byte code strings. I omitted Wasm byte code from events for now.

I also created an issue for adding SemVer to the chain. Once we have that, adding it as an event attribute should be easy.
